import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { deleteRoute, getRoutes, saveRoute, type RouteItem } from '../../api/server'
import { DataTable, type Column } from '../../components/ui/DataTable'
import { Modal } from '../../components/ui/Modal'
import { PageHeader } from '../../components/ui/PageHeader'
export function RoutesPage(){const qc=useQueryClient();const[open,setOpen]=useState(false);const[remarks,setRemarks]=useState('');const[match,setMatch]=useState('');const[action,setAction]=useState('block');const[value,setValue]=useState('');const q=useQuery({queryKey:['routes'],queryFn:getRoutes});const save=useMutation({mutationFn:()=>saveRoute({remarks,match:match.split('\n').map(x=>x.trim()).filter(Boolean),action,action_value:value}),onSuccess:()=>{setOpen(false);qc.invalidateQueries({queryKey:['routes']})}});const del=useMutation({mutationFn:deleteRoute,onSuccess:()=>qc.invalidateQueries({queryKey:['routes']})});const rows=Array.isArray(q.data)?q.data:[];const cols:Column<RouteItem>[]=[{key:'id',header:'ID',render:r=>r.id},{key:'remarks',header:'备注',render:r=>r.remarks||'-'},{key:'match',header:'匹配',render:r=><code>{Array.isArray(r.match)?r.match.join(', '):'-'}</code>},{key:'action',header:'动作',render:r=><span className="badge">{r.action||'-'}</span>},{key:'value',header:'值',render:r=>r.action_value||'-'},{key:'a',header:'操作',render:r=><button className="icon-button danger" onClick={()=>confirm('确认删除该路由规则？')&&del.mutate(r.id)}><Trash2 size={16}/></button>}];return <><PageHeader title="路由规则" description="match 按换行切分；dns/proxy 时显示 action_value。" action={<button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/>添加规则</button>}/><div className="card"><DataTable rows={rows} columns={cols}/></div><Modal open={open} title="添加路由规则" onClose={()=>setOpen(false)}><div className="form-stack"><label className="field"><span>备注</span><input value={remarks} onChange={e=>setRemarks(e.target.value)}/></label><label className="field"><span>匹配条件（每行一条）</span><textarea value={match} onChange={e=>setMatch(e.target.value)}/></label><label className="field"><span>动作</span><select value={action} onChange={e=>setAction(e.target.value)}><option>block</option><option>dns</option><option>direct</option><option>proxy</option></select></label>{['dns','proxy'].includes(action)&&<label className="field"><span>action_value</span><input value={value} onChange={e=>setValue(e.target.value)}/></label>}<button className="button primary" onClick={()=>{if(!match.trim()){toast.error('请输入匹配条件');return}save.mutate()}}>保存</button></div></Modal></>}
